language: julia
env:
  - PYTHON=""
os:
  - linux
  - osx
notifications:
  email: false
julia:
  - nightly
  - 1.1
  - 1.0
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("MNE")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("MNE")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
